export default {
  CHAIN: {
    ETH: 1,
    KLAYTN: 2,
  },
  EXPLORER: {
    ETH: "https://etherscan.io/",
    KLAYTN: "https://scope.klaytn.com/",
  },
  TOKEN_CATE: {
    ETH: 1,
    KLAY: 2,
    ART: 3,
    COLLECT: 4,
    ETC: 5,
  },
  STATUS: {
    WHITELIST: {
      YES: 1,
      NO: 2,
    },
    TX: {
      PENDING: 1,
      START: 2,
      CANCEL: 3,
      FAIL: 4,
      DONE: 7,
    },
    TOKEN: {
      DEPOSIT: 1,
      SELL: 2,
      AUCTION: 3,
      BUY: 4,
      BID: 5,
      NEGO: 6,
      WITHDRAW: 7,
      RETRIVE: 8,
      VAULT: 9,
      SEND: 10,
      MINT: 11,
      BURN: 12,
    },
    NFT: {
      DEPOSIT: 1,
      SELL: 2,
      AUCTION: 3,
      BUY: 4,
      WITHDRAW: 7,
      VAULT: 9,
      SEND: 10,
      MINT: 11,
      BURN: 12,
    },
    AUCTION: {
      PENDING: 1,
      START: 2,
      CANCEL: 3,
      DONE: 7,
      FAIL: 8,
    },
    SELL: {
      PENDING: 1,
      START: 2,
      CANCEL: 3,
      DONE: 7,
      FAIL: 8,
    },
    SALE: {
      PENDING: 1,
      START: 2,
      CANCEL: 3,
      DONE: 7,
      FAIL: 8,
    },
    BUY: {
      START: 2,
      CANCEL: 3,
      DONE: 7,
      FAIL: 8,
    },
    BID: {
      START: 2,
      CANCEL: 3,
      REJECT: 5,
      DONE: 7,
      FAIL: 8,
    },
    NEGO: {
      START: 2,
      CANCEL: 3,
      REJECT: 5,
      DONE: 7,
      FAIL: 8,
    },
    NFT_INFO: {
      USE: 1,
      NOT_USE: 2,
    },
    TOKEN_INFO: {
      USE: 1,
      NOT_USE: 2,
    },
    SALE_QUEUE: {
      PENDING: 1,
      SUCCESS: 2,
      FAIL: 3,
    },
  },
  TYPE: {
    CATEGORY: {
      NFT: 1,
      TOKEN: 2,
    },
    SALE: {
      NORMAL_AUCTION: 1,
      INSTANT_AUCTION: 2,
      DIRECT_SELL: 3,
      NEGOTIABLE_SELL: 4,
    },
    EVENT: {
      AUCTION: 1,
      SELL: 2,
      BUY: 3,
      BID: 4,
      NEGO: 5,
      NFT: 6,
      TOKEN: 7,
    },
    TRADE: {
      AUCTION: 1,
      SELL: 2,
      BUY: 3,
      STAKE: 4,
    },
    STAKE: {
      STAKING: 1,
      UNSTAKING: 2,
      CLAIM_UNSTAKING: 3,
      REWARD: 4,
    },
  },
};
